### PR TITLE
Remove Deli.H3VR Reference

### PR DESCRIPTION
**Pull request by Frityet**

### CODE REVIEW

**Comment by Maiq-The-Dude** [comment]
I didn't know people other than me used this repo. I'm going to let this marinate for a bit because I'm not exactly sure what is happening with the Deli changes yet. This repo may honestly be archived/obsoleted by those.

**Comment by Frityet** [comment]
lol I use this repo all the time, in my new yt video/tutorial I show how to use it

**Comment by Frityet** [comment]
> 
> 
> I didn't know people other than me used this repo. I'm going to let this marinate for a bit because I'm not exactly sure what is happening with the Deli changes yet. This repo may honestly be archived/obsoleted by those.

so now that we do know whats happening

**Comment by Maiq-The-Dude** [comment]
Looks good to me

**Pull request merged**
